add option to continue building on failure when using --recipe-dir
prefix-dev/rattler-build pull request #1023
Opened 2024-08-16 09:33 UTC by KGB99

2024-08-16 11:36 UTC, KGB99 commented
I haven't figured out how to add the option to the CLI, any guidance is appreciated.

2024-08-16 14:39 UTC, baszalmstra requested changes
Do you still need help with the CLI? Looks like you already managed to make it work?

2024-08-16 14:39 UTC, baszalmstra commented on src/lib.rs
> +        cont_on_fail: args.cont_on_fail,
I would personally not specify this in the tool configuration but instead just pass a boolean to the `run_build_from_args` function.

2024-08-16 14:39 UTC, baszalmstra commented on src/opt.rs
> +    pub cont_on_fail: bool,
Can you make this argument a little more descriptive? Perhaps just `continue_on_failure`?

2024-08-16 14:39 UTC, baszalmstra commented on src/opt.rs
> +    /// Only relevant when building multiple recipes with `--recipe-dir`
You can enforce this by adding `requires = "recipe-dir"` to the `#[arg` section below.

2024-08-16 14:56 UTC, baszalmstra commented
Also, can you make sure that the program still exists with an exit code if one of the ouputs failed to build?

2024-08-16 15:48 UTC, KGB99 commented
> Do you still need help with the CLI? Looks like you already managed to make it work?

Yes it seems to work, thank you, i used the wrong command from the CLI myself, so I was confused.

> Also, can you make sure that the program still exists with an exit code if one of the ouputs failed to build?

This would be for a singular recipe right? I believe the latest commit includes that as well.

2025-03-24 13:57 UTC, baszalmstra commented
@wolfv Are you still interested in this PR? Should we upstream the changes?

2025-05-06 12:51 UTC, closed without merging